### PR TITLE
Bump linkie-core version

### PR DESCRIPTION
**Pull request by NoComment1105**
This fixes errors with 1.19 Minecraft classes

### CODE REVIEW

**Comment by gdude2002** [comment]
How test?

**Comment by NoComment1105** [comment]
By running the tests

**Comment by NoComment1105** [comment]
And flicking through classes related to the mappings extension and finding no errors

**Comment by NoComment1105** [comment]
I fired up your lovely little test bot and tested some methods that caused me issues the other day: 
image

image

**Comment by gdude2002** [comment]
in that case, thank!

**Pull request merged**
