### PR TITLE
Paginator and help

### PR DESCRIPTION
**Pull request by Akarys42**
This PR adds the paginator from Kotlin-Discord/bot#6 and the help command from Kotlin-Discord/bot#5.

### CODE REVIEW

**Comment by Akarys42** [comment]
It isn't running any check indeed, but I don't see which checks to
actually run. The only thing I could think of is checking that the command
was invocated inside the command channel, which should be done at the bot
level, right?

>

**Comment by gdude2002** [comment]
The checks defined on the Command object?

**Comment by Akarys42** [comment]
There wasn't a plan about defining bot-wide checks? It would be nice to
have something like that.

**Comment by gdude2002** [comment]
I didn't already have a TODO for that, no, it's more complicated than it
sounds. But we can investigate that later.

**Comment by gdude2002** [comment]
We'll worry about checks later.

**Pull request merged**
