### PR TITLE
Add support for slash command localizations

### PR DESCRIPTION
**Pull request by DRSchlaubi**
# Relevant Issues
kordlib/kord#570

# Description

Discord now added translations for the slash command UI, this PR now acceppts the existing translation strings in name and description fields

### CODE REVIEW

**Comment by gdude2002** [comment]
~~This very much needs testing in the context of the locale resolution changes I put in. You said you'd get around to it, but I haven't heard anything yet?~~

EDIT: Whoops, meant to put that on the other PR.

This one doesn't seem to build, though.

**Comment by DRSchlaubi** [comment]
I would also propose something like a commandBundle, which defaults to the module bundle, because I have a plugin providing commands and translations only used outside the plugin, therefore it doesn't find them in the other plugins module

**Comment by gdude2002** [comment]
Do you mean specifically that commands would be able to specify the bundle they use, or something deeper than that?

**Comment by DRSchlaubi** [comment]
> Do you mean specifically that commands would be able to specify the bundle they use, or something deeper than that?

yes (commands specify their own bundle and default to their module)

**Comment by gdude2002** [comment]
Yeah, no reason we can't do that, should be fairly simple to do

**Comment by gdude2002** [comment]
I've added that in the latest push. This branch still doesn't build, though.

**Comment by DRSchlaubi** [comment]
amazing now I just gotta update the translation logic to use that

**Comment by DRSchlaubi** [comment]
Logic should use the new resolveBundle now

**Comment by gdude2002** [comment]
Still got build issues, though - but that doesn't.. look like your fault? That's an odd one

**Comment by gdude2002** [comment]
Oh, it's because you're on a feature branch - is that still on a kord feature branch?

**Comment by DRSchlaubi** [comment]
afaik the branch is still not merged

**Comment by gdude2002** [comment]
Ah heck, and I'm not on speaking terms with Hope rn either.

Is it at least further ahead than M12?

**Comment by lukellmann** [comment]
> Is it at least further ahead than M12?

Yes, I merged it recently, it's only one commit behind 0.8.x

**Comment by DRSchlaubi** [comment]
> > Is it at least further ahead than M12?
> 
> Yes, I merged it recently, it's only one commit behind 0.8.x

https://github.com/kordlib/kord/pull/570 has not been merged yet

**Comment by lukellmann** [comment]
> > > Is it at least further ahead than M12?
> > 
> > 
> > Yes, I merged it recently, it's only one commit behind 0.8.x
> 
> [kordlib/kord#570](https://github.com/kordlib/kord/pull/570) has not been merged yet

That's correct, my comment wasn't very precise: I merged the main branch into the feature branch, not the other way around.

**Comment by DRSchlaubi** [comment]
Ohh i see, that explains why I was not aware of that branch getting merged, it never got merged

**Comment by gdude2002** [comment]
Now that it's been merged, what's the status of this PR?

**Comment by gdude2002** [comment]
Good work, thanks o7

**Pull request merged**
