### PR TITLE
Add support for interaction internationalization

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by gdude2002** [comment]
Seems fine from a casual review, looking forward to the Kord merge!

**Comment by DRSchlaubi** [comment]
The Discord locales are not that useful, as de_DE is just de

That's why I needed to do something like this

https://github.com/DRSchlaubi/mikbot/blob/30f1093a92ad2656f144788e9c9742d446eeed49/core/database-i18n/src/main/kotlin/dev/schlaubi/mikbot/core/i18n/database/DatabaseI18NPlugin.kt#L15-L33

Also read https://github.com/kordlib/kord/pull/480#issuecomment-1011436238

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/DRSchlaubi/mikbot">mikbot/DatabaseI18NPlugin.kt at 30f1093a92ad2656f144788e9c9742d446eeed49 · DRSchlaubi/mikbot</a></strong></div><div>A modular framework for building Discord bots in Kotlin using Kordex and Kord - mikbot/DatabaseI18NPlugin.kt at 30f1093a92ad2656f144788e9c9742d446eeed49 · DRSchlaubi/mikbot</div></blockquote>

**Comment by gdude2002** [comment]
This PR seems broken as of the two most recent commits - you need to rebase.

**Comment by gdude2002** [comment]
This very much needs testing in the context of the locale resolution changes I put in. You said you'd get around to it, but I haven't heard anything yet?

**Comment by DRSchlaubi** [comment]
I completely forgot this PR, the conversion is no longer necessary, as the resolution changes you did seem to work

**Comment by gdude2002** [comment]
If that's the case, that's excellent - thanks for looking into this.

**Pull request merged**
