### PR TITLE
Add MessageChannel.withTyping()

### PR DESCRIPTION
**Pull request by DRSchlaubi**
Add a similar method to discord.py's [async with typing](https://discordpy.readthedocs.io/en/stable/api.html?highlight=typing#discord.abc.Messageable.typing)

### CODE REVIEW

**Comment by gdude2002** [comment]
Wait, what? I'm pretty sure Kord already has this, no?

**Comment by DRSchlaubi** [comment]
> Wait, what? I'm pretty sure Kord already has this, no?

I couldn't find it

**Comment by DRSchlaubi** [comment]
There only is typeUntil()
https://github.com/kordlib/kord/blob/16fd7ec4a2f8684c33455131ef0e7875d356ca0c/core/src/main/kotlin/behavior/channel/MessageChannelBehavior.kt#L188-L222

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/kordlib/kord">kord/MessageChannelBehavior.kt at 16fd7ec4a2f8684c33455131ef0e7875d356ca0c · kordlib/kord</a></strong></div><div> Idiomatic Kotlin Wrapper for The Discord API. Contribute to kordlib/kord development by creating an account on GitHub.</div></blockquote>

**Comment by gdude2002** [comment]
> There only is typeUntil()

Nope, I'm pretty sure there's a `withTyping` because I've definitely used something like that. It's probably just a different behavior from the one you were expecting?

**Comment by DRSchlaubi** [comment]
> > There only is typeUntil()
> 
> Nope, I'm pretty sure there's a `withTyping` because I've definitely used something like that. It's probably just a different behavior from the one you were expecting?

I actually did to but I couldn't find it

**Comment by DRSchlaubi** [comment]
it's an extension, that's why i didn't find it
https://github.com/kordlib/kord/blob/16fd7ec4a2f8684c33455131ef0e7875d356ca0c/core/src/main/kotlin/behavior/channel/MessageChannelBehavior.kt#L282-L314

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/kordlib/kord">kord/MessageChannelBehavior.kt at 16fd7ec4a2f8684c33455131ef0e7875d356ca0c · kordlib/kord</a></strong></div><div> Idiomatic Kotlin Wrapper for The Discord API. Contribute to kordlib/kord development by creating an account on GitHub.</div></blockquote>

**Pull request closed without merging**
