### PR TITLE
Update to Kord M10

### PR DESCRIPTION
**Pull request by lukellmann**
Kord 0.8.0-M10 included a major refactor with breaking changes, this PR updates kordex to work with the latest snapshots by updating imports, types and fixing deprecations.

~However this will not work with 0.8.0-M10 directly because of a small oversight (missing `command` in `AutoCompleteInteraction`) that was fixed right after M10.~
I added a drop in replacement for the missing `command` property.

### CODE REVIEW

**Comment by gdude2002** [comment]
So, what's the exact plan here? Wait until M11?

**Comment by lukellmann** [comment]
> So, what's the exact plan here? Wait until M11?

That would be the easiest option.

It also wouldn't be hard to (temporarily) replace the missing `command` property with an extension property if you want to do a release before M11.

**Comment by gdude2002** [comment]
I'm not likely to have the time/brainpower to work on this for a while, so I guess it's gonna have to be waiting for a bit.

**Comment by lukellmann** [comment]
This is now compatible with M10.

**Comment by gdude2002** [comment]
Looks good to me - did you have a chance to test it with the test bot?

**Comment by lukellmann** [comment]
> Looks good to me - did you have a chance to test it with the test bot?

Where do I find that bot? Is it part of this repo?

**Comment by gdude2002** [comment]
It's in the `test` source set

**Comment by lukellmann** [comment]
If you mean the one in the `kord-extensions` module: it seems to work, I did not quite understand all of the commands but there were no errors.

**Comment by gdude2002** [comment]
Thanks for that!

**Pull request merged**
