### PR TITLE
Add the duration parser utility

### PR DESCRIPTION
**Pull request by Akarys42**
This PR adds a (sort of) standalone duration parser. 

I decided to not hook it up to the argument parser because I didn't actually need it, do you think it is a good idea to still hook it up?

### CODE REVIEW

**Comment by ks129** [comment]
I think maybe this should allow using multiple ways to provide time unit (`m|min|minute(s)`, `s|sec|second(s)` etc.)?

**Comment by Akarys42** [comment]
The magic number is just the 10 on line 33, do we really need a comment for that?

**Comment by gdude2002** [comment]
Well, I wouldn't be asking if I knew what it did!

**Comment by Akarys42** [comment]
`mi` and `mo` sounds good to me, it is less ambiguous this way.

**Pull request merged**
