### PR TITLE
Add Markdown Sanitizer functionality

### PR DESCRIPTION
**Pull request by DRSchlaubi**
JDA had these functions as well so might be helpful here too

### CODE REVIEW

**Comment by gdude2002** [comment]
Is this ported from JDA?

**Comment by gdude2002** [comment]
It looks like it's ported from JDA.

**Comment by DRSchlaubi** [comment]
The only thing ported from JDA is the docs string on [contentDisplay]

**Comment by DRSchlaubi** [comment]
Superseded by kordlib/kord#521

**Pull request closed without merging**
