### PR TITLE
Open up converters

### PR DESCRIPTION
**Pull request by NyCodeGHG**
develop

### CODE REVIEW

**Comment by NyCodeGHG** [comment]
oops i guess that went a bit wrong

**Comment by NyCodeGHG** [comment]
ok, for whatever reason github's cli did not let me fill out the pr template.
I need do modify some stuff in a converter, but i can't extend it because it's not open, thats it basically.

**Comment by gdude2002** [comment]
Can you explain what your use-case is here? I'd be curious to know whether there's a better option first

**Comment by NyCodeGHG** [comment]
I have [this converter](https://github.com/mikbot/hafalsch/blob/a00f5416d639c52621cec79b00bccef0d4a02a2a/bot/src/main/kotlin/dev/schlaubi/hafalsch/bot/command/AutoCompletingArgument.kt#L18-L21) but i need to override toOptional and provide my own subclass of SingleToOptionalConverter and need to also set the autocomplete lambda in the builder there. But I just realized that it would be smarter to make sure SingleToOptionalConverter uses the same builder options

**Comment by gdude2002** [comment]
It's worth noting that everything is type-safe here, including the builders themselves, so you could reasonably take a generic ConverterBuilder type here - but yeah, I'm not sure to what extent that helps you.

We could open these, I guess, but it's worth noting that these "converter converters" are really only meant for automatically wrapping other converters. But either way, let's chat on Discord a little so we can see where we're at.

**Comment by NyCodeGHG** [comment]
Closing because use case can be done otherwise

**Pull request closed without merging**
