### PR TITLE
Add an optional map descriptors option for mappings, and add translation support for Manage Events

### PR DESCRIPTION
**Pull request by sschr15**
Translations are needed for `permission.manageEvents` now

### CODE REVIEW

**Comment by sschr15** [comment]
apparently idea pulled really weirdly ono

**Comment by gdude2002** [comment]
looks like your branch wasn't up to date

**Comment by sschr15** [comment]
apparently

**Comment by sschr15** [comment]
Closing as #118 fixes my outdated upstream

**Pull request closed without merging**
